Repository AY2324S2-CS2103T-F11-1/tp, pull requests merged in 2024-03, with the labels that each got.

#15 docs: Update AboutUs details
  docs/AboutUs.md
  docs/images/shawn.png
Labels: type.Documentation

#25 docs: Update README
  README.md
  docs/index.md
Labels: type.Documentation

#32 docs: Add user stories and use cases
  .github/pull_request_template.md
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#42 feat: Add mark command to mark participation scores
  README.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#44 Branch remove tag
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/TagDoesNotExistException.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveTagCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.High

#51 ui: Modify color of week labels
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
Labels: type.Story, priority.Low

#52 Feature: FilterCommand
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsTagPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: type.Story, priority.High

#55 Update DeveloperGuide for undo/redo
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#56 fix: Fix parsing logic for mark command
  build.gradle
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, type.Bug

#58 docs: Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/dg/MarkSequenceDiagram.png
  docs/assets/dg/SDCommitAddressbook.png
  docs/assets/dg/SDMarkParticipation.png
  docs/assets/dg/SDMarkParticipationCommandResult.png
  docs/diagrams/MarkSequenceDiagram.puml
  docs/diagrams/SDCommitAddressbook.puml
  docs/diagrams/SDMarkParticipation.puml
  docs/diagrams/SDMarkParticipationCommandResult.puml
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
Labels: priority.High, type.Documentation

#70 feat: Modify participation scores to be greater than one
  src/main/java/seedu/address/logic/commands/MarkParticipationCommand.java
  src/test/java/seedu/address/logic/commands/MarkParticipationCommandTest.java
Labels: type.Story, priority.High
