Repository AY2324S2-CS2103T-F11-1/tp, pull requests merged in 2024-04, with the labels that each got.

#79 Dylan/Add checks to prevent negative scores
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UnmarkAllAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAllParticipationCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkParticipationCommand.java
  src/test/java/seedu/address/logic/commands/UnmarkAllAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAllParticipationCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkParticipationCommandTest.java
Labels: type.Enhancement, priority.High

#80 docs: Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/img.png
  docs/index.md
Labels: priority.High, type.Documentation

#147 edit the error messages for gradecommand
  src/main/java/seedu/address/logic/parser/GradeAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug

#151 Branch commands reset bugfix
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/RemoveAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagFromAllCommand.java
Labels: type.Bug

#154 Branch bugfix adda duplicates
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/MarkAllAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/MarkAllParticipationCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/MarkParticipationCommand.java
  src/main/java/seedu/address/logic/commands/RemoveAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAllAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAllParticipationCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkParticipationCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveAssignmentCommandParser.java
  src/main/java/seedu/address/model/person/Assignment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/GradeAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveAssignmentCommandTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug

#153 docs: Update UG
  docs/UserGuide.md
  docs/images/ug/filterStudentExample.png
  docs/images/ug/gradeAssignmentExample.png
  docs/img.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Documentation

#158 Dylan/docs/dg: Update Use Cases
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#159 docs: Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/dg/MarkParticipationSequenceDiagram.png
  docs/assets/dg/MarkSequenceDiagram.png
  docs/assets/dg/SDCommitAddressbook.png
  docs/assets/dg/SDMarkParticipation.png
  docs/assets/dg/SDMarkParticipationCommandResult.png
  docs/diagrams/MarkParticipationSequenceDiagram.puml
  docs/diagrams/MarkSequenceDiagram.puml
  docs/diagrams/SDCommitAddressbook.puml
  docs/diagrams/SDMarkParticipation.puml
  docs/diagrams/SDMarkParticipationCommandResult.puml
Labels: type.Documentation

#162 Dylan/docs: Refactor from AB3 to NTP terms
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/dg/BetterModelClassDiagram.png
  docs/images/dg/ModelClassDiagram.png
  docs/images/dg/StorageClassDiagram.png
Labels: priority.High, type.Documentation

#163 Dylan/docs: Add implementation of grade command
  docs/DeveloperGuide.md
  docs/assets/dg/SDCommitAddressbook.png
  docs/assets/dg/SDGradeAssignmentCommitAddressbook.png
  docs/assets/dg/SDMarkParticipationCommitAddressbook.png
  docs/diagrams/GradeAssignmentSequenceDiagram.puml
  docs/diagrams/SDGradeAssignment.puml
  docs/diagrams/SDGradeAssignmentCommandResult.puml
  docs/diagrams/SDGradeAssignmentCommitAddressbook.puml
  docs/diagrams/SDMarkParticipationCommitAddressbook.puml
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
Labels: priority.High, type.Documentation

#164 docs: Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/dg/GradeAssignmentSequenceDiagram.png
  docs/assets/dg/MarkParticipationSequenceDiagram.png
  docs/assets/dg/SDGradeAssignment.png
  docs/assets/dg/SDGradeAssignmentCommandResult.png
  docs/assets/dg/SDMarkParticipation.png
  docs/diagrams/MarkParticipationSequenceDiagram.puml
  docs/diagrams/SDMarkParticipation.puml
  docs/diagrams/SDMarkParticipationCommitAddressbook.puml
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Documentation

#165 docs: Update DG implementation
  docs/DeveloperGuide.md
  docs/assets/dg/FilterCommandSequenceDiagram.png
  docs/assets/dg/SDFilterCommandResult.png
  docs/assets/dg/SDFilterStudents.png
  docs/diagrams/FilterCommandSequenceDiagram.puml
  docs/diagrams/MarkParticipationSequenceDiagram.puml
  docs/diagrams/SDFilterCommandResult.puml
  docs/diagrams/SDFilterStudents.puml
  src/main/java/seedu/address/model/person/PersonContainsTagPredicate.java
Labels: type.Documentation

#166 Dylan/docs: Edit site header for PDF format
  docs/_sass/minima/_base.scss
Labels: priority.High, type.Documentation

#168 docs: Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/GradeAssignmentCommand.java
Labels: type.Documentation
